[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["cd server && npm install"]

[phases.build]
cmds = ["echo 'No build needed for backend'"]

[start]
cmd = "cd server && node index.js"

